#!/bin/bash

# Stripe Setup Script for Athena E-commerce
# This script helps configure Stripe payment integration

set -e

echo "======================================"
echo "  Athena Stripe Payment Setup"
echo "======================================"
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check if .env file exists
if [ ! -f ".env" ]; then
    echo -e "${YELLOW}Creating .env file from .env.example...${NC}"
    if [ -f ".env.example" ]; then
        cp .env.example .env
        echo -e "${GREEN}✓ .env file created${NC}"
    else
        echo -e "${RED}✗ .env.example not found. Creating new .env file...${NC}"
        touch .env
    fi
    echo ""
fi

echo -e "${YELLOW}Step 1: Get your Stripe API keys${NC}"
echo "--------------------------------------"
echo "1. Go to https://dashboard.stripe.com/test/apikeys"
echo "2. Copy your 'Secret key' (starts with sk_test_)"
echo "3. Copy your 'Publishable key' (starts with pk_test_)"
echo ""

# Prompt for Stripe Secret Key
echo -e "${YELLOW}Enter your Stripe Secret Key (sk_test_...):${NC}"
read -r STRIPE_SECRET_KEY

if [ -z "$STRIPE_SECRET_KEY" ]; then
    echo -e "${RED}✗ Stripe Secret Key is required${NC}"
    exit 1
fi

# Prompt for Stripe Publishable Key
echo -e "${YELLOW}Enter your Stripe Publishable Key (pk_test_...):${NC}"
read -r STRIPE_PUBLISHABLE_KEY

if [ -z "$STRIPE_PUBLISHABLE_KEY" ]; then
    echo -e "${RED}✗ Stripe Publishable Key is required${NC}"
    exit 1
fi

echo ""
echo -e "${YELLOW}Step 2: Setup Stripe Webhooks${NC}"
echo "--------------------------------------"
echo "For local development, you can use Stripe CLI:"
echo "1. Install Stripe CLI: https://stripe.com/docs/stripe-cli"
echo "2. Run: stripe login"
echo "3. Run: stripe listen --forward-to localhost:3001/api/webhooks/stripe"
echo "4. Copy the webhook signing secret (whsec_...)"
echo ""
echo "For production, create a webhook endpoint at:"
echo "https://dashboard.stripe.com/webhooks"
echo "Point it to: https://your-domain.com/api/webhooks/stripe"
echo "Select events: payment_intent.succeeded, payment_intent.payment_failed"
echo ""

echo -e "${YELLOW}Enter your Stripe Webhook Secret (whsec_...) [optional]:${NC}"
read -r STRIPE_WEBHOOK_SECRET

# Update or add Stripe keys to .env
echo ""
echo -e "${YELLOW}Updating .env file...${NC}"

# Remove existing Stripe keys if present
sed -i.bak '/^STRIPE_SECRET_KEY=/d' .env 2>/dev/null || true
sed -i.bak '/^STRIPE_PUBLISHABLE_KEY=/d' .env 2>/dev/null || true
sed -i.bak '/^STRIPE_WEBHOOK_SECRET=/d' .env 2>/dev/null || true

# Add new keys
echo "STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY" >> .env
echo "STRIPE_PUBLISHABLE_KEY=$STRIPE_PUBLISHABLE_KEY" >> .env

if [ -n "$STRIPE_WEBHOOK_SECRET" ]; then
    echo "STRIPE_WEBHOOK_SECRET=$STRIPE_WEBHOOK_SECRET" >> .env
fi

# Remove backup file
rm -f .env.bak

echo -e "${GREEN}✓ Stripe keys added to .env${NC}"
echo ""

# Create a public config file for frontend
echo -e "${YELLOW}Creating public Stripe config for frontend...${NC}"

cat > public/js/stripe-config.js << EOF
// Stripe Configuration for Frontend
// This file is auto-generated by scripts/setup-stripe.sh
// DO NOT commit this file to version control

window.STRIPE_CONFIG = {
  publishableKey: '$STRIPE_PUBLISHABLE_KEY',
};
EOF

echo -e "${GREEN}✓ Created public/js/stripe-config.js${NC}"
echo ""

# Add to .gitignore if not already there
if ! grep -q "public/js/stripe-config.js" .gitignore 2>/dev/null; then
    echo "public/js/stripe-config.js" >> .gitignore
    echo -e "${GREEN}✓ Added stripe-config.js to .gitignore${NC}"
fi

echo ""
echo -e "${GREEN}======================================"
echo "  Stripe Setup Complete!"
echo "======================================${NC}"
echo ""
echo "Next steps:"
echo "1. Start your backend server: npm run dev:api"
echo "2. Start your frontend server: npm run dev:server"
echo "3. Test a payment at: http://localhost:3000/checkout.html"
echo ""
echo "For webhook testing:"
echo "  stripe listen --forward-to localhost:3001/api/webhooks/stripe"
echo ""
echo -e "${YELLOW}Remember: These are TEST keys. Use different keys for production!${NC}"
echo ""
